
namespace Gatekeeper.Web.UI.Logging
{
    /// <summary>
    /// Contains the log messages.
    /// </summary>
    /// <remarks>
    /// 	<para>
    /// 		<list type="table">
    /// 			<listheader>
    /// 				<description>modified</description>
    /// 				<description>by</description>
    /// 				<description>description</description>
    /// 			</listheader>
    /// 			<item>
    /// 				<description>5/17/2008</description>
    /// 				<description>Chamith</description>
    /// 				<description>initial code</description>
    /// 			</item>
    /// 		</list>
    /// 	</para>
    /// </remarks>
    public class Messages
    {
        /// <summary>
        /// Log message for entering a method.
        /// </summary>
        public const string MethodEnter = "Entered Method";
        /// <summary>
        /// Log message for leaving a method.
        /// </summary>
        public const string MethodLeave = "Leaving Method";

        /// <summary>
        /// Log message for an exception occurred in the system.
        /// </summary>
        public const string ExceptionOccurred = "Exception Occurred";

        /// <summary>
        /// Log message for an exception sunk by the system.
        /// </summary>
        public const string ExceptionOccurredAndSunk = "Exception Occurred and Sunk";

        /// <summary>
        /// Log message for a rethrown exception, which is also occurred in the system.
        /// </summary>
        public const string ExceptionOccurredAndRethrown = "Exception Occurred and Rethrown";

        /// <summary>
        /// Log message for a exception, generated by the system.
        /// </summary>
        public const string ExceptionGenerated = "Exception Generated";

    }
}
